[package]
name = "mrkl"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]

[features]
default = ["digest-hash"]

[dependencies.digest-hash]
git = "https://github.com/mzabaluev/digest-hash-rs.git"
optional = true

[dev-dependencies]
sha2 = "0.7"
