[package]
name = "mrkl"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]

[features]
default = ["digest-hasher"]

digest-hasher = ["digest", "byteorder"]

[dependencies]
digest = { version = "0.7", optional = true }
byteorder = { version = "1.2", optional = true }
